
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]
  - job_name: "iot_app"
    static_configs:
      - targets: ["host.docker.internal:50051"]

